# Generated by Django 3.1.10 on 2021-09-08 19:09

import json
from itertools import islice

from django.db import migrations, models

import fleet.models


def populate(apps, schema_editor):
    Fleet = apps.get_model('fleet', 'Fleet')
    db_alias = schema_editor.connection.alias

    # https://www.geeksforgeeks.org/read-json-file-using-python/
    file = open('core/data.json')
    data = json.load(file)

    # https://docs.djangoproject.com/en/3.2/ref/models/querysets/#bulk-create
    batch_size = 50
    objs = (Fleet(id=fleet['id'], name=fleet['name']) for fleet in data['fleets'])

    while True:
        batch = list(islice(objs, batch_size))
        if not batch:
            break
        Fleet.objects.using(db_alias).bulk_create(batch, batch_size)


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fleet',
            fields=[
                ('id', models.CharField(default=fleet.models.generate_id, editable=False, help_text='id', max_length=6, primary_key=True, serialize=False, verbose_name='id')),
                ('name', models.CharField(help_text='name', max_length=255, verbose_name='name')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='created', verbose_name='created')),
                ('updated', models.DateTimeField(auto_now=True, help_text='updated', verbose_name='updated')),
                ('archived', models.BooleanField(default=False, help_text='archived', verbose_name='archived')),
            ],
            options={
                'verbose_name': 'fleet',
                'verbose_name_plural': 'fleets',
                'db_table': 'fleet.fleets',
            },
        ),
        migrations.RunPython(populate)
    ]
